//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrutoNetoApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Radnik
    {
        public int Id_radnika { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Adresa { get; set; }
        public double Iznos_NP { get; set; }
        public double Iznos_BP { get; set; }
        public double OZOP { get; set; }
        public double Porez { get; set; }
        public double PNTR { get; set; }
        public double ZNTR { get; set; }
        public double NNTR { get; set; }
        public double UDNTR { get; set; }
        public double PNTP { get; set; }
        public double ZNTP { get; set; }
        public double UDNTP { get; set; }
        public double TPZI { get; set; }
    }
}
